name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [ published, created, edited ]

env:
  CMAKE_ARGS: "-DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake"

jobs:
  Build:
    strategy:
      matrix:
        compiler: [ g++, clang++ ]
        BUILD_TYPE: [ Release, Debug ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg

      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh && vcpkg integrate install

      - name: Install vcpkg dependencies
        run: cd vcpkg && ./vcpkg install cli pcapplusplus

      - name: Install boost
        run: sudo apt-get install -y libboost-all-dev

      - name: CMake configure
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
          $CMAKE_ARGS

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.BUILD_TYPE }}
